model: unet_small2_yuv_quant

hidden:
  num_blocks: 4
  num_bits: 16
  in_channels: 3
  out_channels: 3
  z_channels: 64
  normalization: 'group'
  activation: 'gelu'
  last_tanh: True

hidden_orig:
  num_blocks: 4
  num_bits: 16
  in_channels: 3
  out_channels: 3
  z_channels: 64
  normalization: 'batch'
  activation: 'relu'
  last_tanh: False

unet_small2_quant: # quantization friendly unet2
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 8
    activation: 'relu'
    normalization: 'batch'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True

unet_small2_yuv_quant:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 1
    out_channels: 1
    z_channels: 16
    num_blocks: 8
    activation: 'relu'
    normalization: 'batch'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True

unet_tiny_yuv_quant:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 1
    out_channels: 1
    z_channels: 8
    num_blocks: 6
    activation: 'relu'
    normalization: 'batch'
    z_channels_mults: [1, 1, 2, 4]
    last_tanh: True